# GitHub Actionsのワークフロー構文
# https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

# コンテキストおよび式の構文
# https://docs.github.com/ja/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
# 文字列ではなく式として判定する ${{ <expression> }}

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
    # - 'FILE_NAME' # ここに列挙されたファイルがpushされても無視する
    - 'README.md'
    - 'analysis_options.yaml'
    - '.gitignore'
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  #
  # Build for Android
  #
  build_Android:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # チェックアウト
      - name: Checks-out my repository 
        uses: actions/checkout@v2

      # Flutter のインストール clone がはやい
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git

      # PATH を通す
      - name: Add path
        run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      # パッケージのダウンロード
      - name: Download Flutter packages
        run: flutter pub get

      # Secrets からrelease.jks を生成
      - name: Create release.jks
        run: echo -n ${{ secrets.ANDROID_KEY_JKS }} | base64 -d > android/release.jks

      # Secrets から key.properties を生成
      - name: Create key.properties
        run: |
          echo 'storeFile=release.jks' > android/key.properties
          echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' >> android/key.properties
          echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' >> android/key.properties
          cat android/key.properties

      # App Bundle を生成
      - name: Building Android appbundle
        run: flutter build appbundle --build-number ${GITHUB_RUN_NUMBER}

# jobs:
#   #
#   # Build for iOS
#   #
#   build_iOS: # jobに名前をつけられる

#     name: Build for iOS # GitHubに表示されるジョブの名前
#     runs-on: macos-latest # ジョブを実行するマシーンの種類

#     steps: #一連のタスク

#       # チェックアウト
#       - name: Checks-out my repository 
#         uses: actions/checkout@v2
      
#       # Flutter のインストール clone がはやい
#       - name: Install Flutter
#         run: git clone https://github.com/flutter/flutter.git

#       # PATH を通す
#       - name: Add path
#         run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

#       # # マーケットプレイスの actions を使う場合
#       # - uses: subosito/flutter-action@v1
#       #   with:
#       #     channel: 'beta'

#       # パッケージのダウンロード
#       - name: Download Flutter packages
#         run: flutter pub get

#       # 証明書の生成
#       - name: Import Provisioning Profile
#         run: |
#           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
#           touch ~/Library/MobileDevice/Provisioning\ Profiles/distribution.mobileprovision
#           echo -n '${{ secrets.PROVISIONING_PROFILE }}' | base64 -d -o ~/Library/MobileDevice/Provisioning\ Profiles/sadistributionmple_dist.mobileprovision
    
#       # 署名をする
#       - name: Import Code-Signing Certificates
#         uses: Apple-Actions/import-codesign-certs@v1
#         with:
#           p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
#           p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
      
#       # ipa ファイルの出力
#       - name: Create ipa file
#         # GITHUB_RUN_NUMBER をビルドナンバーに指定することで被りがないようにしている。
#         run: flutter build ipa --export-options-plist=ExportOptions.plist --build-number ${GITHUB_RUN_NUMBER}
      
#       # AppStoreConnect にアップロードする
#       - name: Upload to AppStoreConnect
#         run: xcrun altool --upload-app -f "./build/ios/ipa/github_actios_sample.ipa" -u "${{ secrets.APPLE_ID }}" -p "${{ secrets.APPLE_APP_PASS }}" 
        



  #     # Slackに通知を送る
  #     # 参考: https://spinners.work/posts/github-actions-context/
  #     - name: Send notification to slack
  #       uses: tokorom/action-slack-incoming-webhook@main
  #       env:
  #         INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #       with:
  #         text: Hello, Slack!